for check
AndriiMan/String_Task_1 pull request #1
Opened 2021-06-16 14:21 UTC by AndriiMan

For check

2021-06-17 03:25 UTC, AndriiMan commented
Fixed all that Anna wrote, after first PR review.

2021-06-17 08:10 UTC, AnnaDremluga commented on src/com/company/Main.java
> +        System.out.println(equalsString ? '"' + str1 + '"' + " is equal to " + '"' + str2 + '"' :
It's better to not do like this. The reasons: not easy to understand, is error-prone (easy to mix args)/ Ternary operator inside System.out.print is awful. Do not do something just because you can. Always try to create clear, neat, understandeble and simple code as much as possible.  One more important thing - what didi you learn about strings, it's concatenation and its and performanse?

2021-06-17 20:54 UTC, AnnaDremluga requested changes
Please, pay attention to my comment

2021-06-22 07:25 UTC, AnnaDremluga approved these changes

2021-06-22 08:01 UTC, merged